### ISSUE TITLE
Install ffmpeg

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/SimuMole#125]
In order to produce mp4 movies successfully (MD videos), please install ffmpeg.
In my computer, I needed to open CMD as an administrator, and run the following command:
`conda install -c conda-forge ffmpeg`
If you install through conda differently, do that.

Write "done" when you finish.

**Comment by Nitzan810** [comment]
done

**Comment by EyalFaygen** [comment]
done

**Comment by OrYasso** [comment]
done

**Comment by MichaelShohat** [comment]
done

**Comment by IlanitSmul** [comment]
done
