### ISSUE TITLE
Install WeTransfer packages

### ISSUE THREAD

**Issue by Nitzan810** [TechnionYP5779/SimuMole#128]
Open either cmd or the PyCharm terminal and execute the following commands:
pip install python-magic-bin==0.4.14
pip install py3wetransfer

These packages are needed to use the external storage service for the emails.
Please write "done" when finished.

**Comment by EyalFaygen** [comment]
done

**Comment by OrYasso** [comment]
done

**Comment by HadadIdan** [comment]
done

**Comment by IlanitSmul** [comment]
done

**Comment by MichaelShohat** [comment]
done
