### ISSUE TITLE
Learn basic Unity usage

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/SimuMole#19]
following #16, basic Unity knowledge is needed from every team member.
Luckily enough, you can learn various aspects of the program using special learning projects.
1) Open Unity
2) Go to the "Learn" tab:
![image](https://user-images.githubusercontent.com/44426929/51493780-10d71180-1dbf-11e9-9cc5-f33a1eb94f6c.png)
3) Follow each of the projects to learn different necessary parts of Unity.

Comment "Done" when you finished with the four of them.

**Comment by OrYasso** [comment]
Done

**Comment by HadadIdan** [comment]
Done (of course)

**Comment by EyalFaygen** [comment]
done

**Comment by elizabethyeshaayahu320** [comment]
Done

**Comment by Nitzan810** [comment]
done

**Comment by MichaelShohat** [comment]
done
