### ISSUE TITLE
Set up a meeting with the Client

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/SimuMole#35]
We want to ask a few questions regarding:
1. The constants in some of the formulas we found to calculate the energy of a molecule.
2. The abstraction we are planning to use (atom-level in contrast to amino acids).
3. Request to point us to a chemistry expert.

**Comment by EyalFaygen** [comment]
Contacted the client, she is available in the workweek mornings. We will set a time and date that fits most.
Will update.

**Comment by HadadIdan** [comment]
Obsolete
