### ISSUE TITLE
create a landing page

### ISSUE THREAD

**Issue by EyalFaygen** [TechnionYP5779/SimuMole#39]
includes:
- welcome message
- upload user pdb files
- insert protein ID
- move to next screen

should also include basic design

**Comment by EyalFaygen** [comment]
relevant commits:
21f269c06bd2f688efa9ed0a858c6ef58a69a082
1e96fceea7a0b20b93e7207883711f987aa2919b
b4368e93896f14f38be9d1e959887d74aac7cd7b
c21182530c0fa20c77a60b963a54658d6773a7de
c8adb35da7abf33aba8de8ae46307023bb799277
 a2049121650c2d2d3ad3915ff70f48092065fc2e

**Comment by HadadIdan** [comment]
Upload pdb files: https://github.com/TechnionYP5779/SimuMole/commit/29ebac3479614602af3e86ec1233fe8c63f289c6 , and the commits from this pr: https://github.com/TechnionYP5779/SimuMole/pull/66

**Comment by IlanitSmul** [comment]
See the following pull requests: #56, #74, #88
