### ISSUE TITLE
Follow Django tutorial to create a web-app and understand it's structure

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/SimuMole#51]
Every team member should understand Django web-app's structure. Since it's a new platform for most of us, a good idea is to follow this [tutorial](https://docs.djangoproject.com/en/2.2/intro/tutorial01/) or a similar one. Once we have enough understanding of this platform we will be able to get a working demo for our project, so this is urgent.

**Comment by HadadIdan** [comment]
follow up to #43

**Comment by HadadIdan** [comment]
Done (waiting for others)

**Comment by OrYasso** [comment]
Done

**Comment by Nitzan810** [comment]
Done

**Comment by MichaelShohat** [comment]
Done

**Comment by IlanitSmul** [comment]
Done

**Comment by EyalFaygen** [comment]
all done
