### ISSUE TITLE
stick footer to the end of the page in base.html

### ISSUE THREAD

**Issue by EyalFaygen** [TechnionYP5779/SimuMole#55]
currently its being placed dynamically and it looks bad if the page is not full.

**Comment by IlanitSmul** [comment]
before cf6cd4f53d7a4c0714cccae82b91805b1d7c04d3:
![image](https://user-images.githubusercontent.com/37686204/56119907-affe4600-5f75-11e9-996b-d2ba3b950ede.png)

after cf6cd4f53d7a4c0714cccae82b91805b1d7c04d3:
![image](https://user-images.githubusercontent.com/37686204/56119928-b8568100-5f75-11e9-8f8c-379069a3394b.png)
