### ISSUE TITLE
Fix PDB merging function

### ISSUE THREAD

**Issue by Nitzan810** [TechnionYP5779/SimuMole#86]
The current PDB merge method we are using (loading two molecules and saving them with the pymol cmd) always results in a failed simulation even after fixing.

Fortunatly I found a method that works:
1. Copy both files one after another into a single file.
2. From the top file delete the lines beggining with "MASTER" or "END".
3. From the bottom file delete the line beggining with "HEADER".
4. Fix them with the PDB fixer.

This method might produce ugly looking structures like this:
![pdb1](https://user-images.githubusercontent.com/44426817/56855036-bcf14100-6948-11e9-9e44-d871d4a4d905.png)

Which is why you want to move it through the fixer, which will make it look good again:
![pdb2](https://user-images.githubusercontent.com/44426817/56855041-d5615b80-6948-11e9-8546-b76b91bf1afc.png)

**Comment by HadadIdan** [comment]
Where have you encountered that? Have you been using the most recent version of the project? Because I know for a fact that the current way we merge and simulate work for Michael.

**Comment by Nitzan810** [comment]
How are you merging the files then?
From what I saw we use the pymol cmd to load 2 files and then save them.
Did we change that?

**Comment by HadadIdan** [comment]
Try pulling the latest version from master. I suspect you are working on an older version.

**Comment by Nitzan810** [comment]
Doesn't work for me, did it through the webserver after doing a pull and I got this exception:

ValueError: No template found for residue 38 (LEU).  The set of atoms matches LEU, but the bonds are different.

**Comment by MichaelShohat** [comment]
After googling the error 2 explanations are available:

- One or both of the pdb files requires fixing manually - not within our field of study.
- Make sure we're using pdbfixer the right way - https://github.com/pandegroup/pdbfixer/issues/76

Try running with 6DY4 5ZKH
