### ISSUE TITLE
undersant how to extract the relevant info from the user files

### ISSUE THREAD

**Issue by EyalFaygen** [TechnionYP5779/SimuMole#9]
create a wiki page explaining the process

**Comment by elizabethyeshaayahu320** [comment]
In order to use Cimera they are unnecessary.
https://github.com/TechnionYP5779/SimuMole/wiki/files-we-got-from-the-client

**Comment by elizabethyeshaayahu320** [comment]
just to show how Cimera shows the protein:
![image](https://user-images.githubusercontent.com/44428417/51083345-58a3cc00-1721-11e9-8a5c-302dc49d2c89.png)

**Comment by elizabethyeshaayahu320** [comment]
Preset - > Interactive 2  : shows in very similar way to the video the client sent us
![image](https://user-images.githubusercontent.com/44428417/51083536-9fdf8c00-1724-11e9-9f0c-81e7171c281e.png)

**Comment by elizabethyeshaayahu320** [comment]
![image](https://user-images.githubusercontent.com/44428417/51182590-60a56c80-18d7-11e9-97e7-b326df4c0480.png) 
I added file explaining what information is stored in those files for each atom. calles "PDB file"
