### ISSUE TITLE
make a presentation for the mid-semester meeting

### ISSUE THREAD

**Issue by EyalFaygen** [TechnionYP5779/SimuMole#91]

**Comment by EyalFaygen** [comment]
hey all,
@OrYasso , @Nitzan810 and my self filled the presentation template Ilanit provided.
its available via [this link](https://drive.google.com/open?id=1upiWyElu7NOLG3mwNr0FwYM_TfFxFD8x)

please have a look at it and feel free to comment

@IlanitSmul  @MichaelShohat @HadadIdan

**Comment by IlanitSmul** [comment]
The presentation after design changes: [link](https://drive.google.com/file/d/1QMYdY4EKShzDaJOtD5XKTa2jxFhqWbCI/view)

**Comment by MichaelShohat** [comment]
The presentation that was shown in class, might have some small changes by myself and Idan - [link](https://drive.google.com/open?id=1l9bQpxJKxRygYXxnZ8dRnwi7CDjBKdOo)
